;;;; src/tables/cmap-4.lisp — (parse-cmap-4 d off) -> a
;;;; hash-table (eql) codepoint->gid for one cmap subtable at absolute byte
;;;; offset OFF in font bytes D. EXCLUDE gid 0 (fontTools policy).
;;;; Readers: (u8 d o)(u16 d o)(s16 d o)(u32 d o) big-endian absolute. Pure CL.
(in-package #:scribe)

(defun parse-cmap-4 (d off)
  (let* ((seg-count-x2 (u16 d (+ off 6)))
         (seg (floor seg-count-x2 2))
         (end-codes (make-array seg :element-type 'fixnum))
         (start-codes (make-array seg :element-type 'fixnum))
         (id-deltas (make-array seg :element-type 'fixnum))
         (id-range-offsets (make-array seg :element-type 'fixnum))
         (result (make-hash-table :test 'eql)))
    (declare (fixnum seg))
    (dotimes (i seg)
      (setf (aref end-codes i) (u16 d (+ off 14 (* i 2)))))
    (dotimes (i seg)
      (setf (aref start-codes i) (u16 d (+ off 16 (* seg 2) (* i 2)))))
    (dotimes (i seg)
      (setf (aref id-deltas i) (s16 d (+ off 16 (* seg 4) (* i 2)))))
    (dotimes (i seg)
      (setf (aref id-range-offsets i) (u16 d (+ off 16 (* seg 6) (* i 2)))))
    (dotimes (i (1- seg))
      (let ((start (aref start-codes i))
            (end (aref end-codes i))
            (delta (aref id-deltas i))
            (iro (aref id-range-offsets i)))
        (declare (fixnum start end delta iro))
        (loop for c from start to end
              for gid = (if (zerop iro)
                            (logand (+ c delta) #xFFFF)
                            (let* ((iro-addr (+ off 16 (* seg 6) (* i 2)))
                                   (g (u16 d (+ iro-addr iro (* 2 (- c start))))))
                              (if (zerop g) 0 (logand (+ g delta) #xFFFF))))
              unless (zerop gid)
              do (setf (gethash c result) gid))))
    result))